name: Run Selenium BDD Feature Files

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Select a feature file to run'
        required: true
        default: 'RegistrationTest'

jobs:
  run-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Modify this based on your Java version
          distribution: 'temurin'

      - name: Install Maven
        uses: actions/setup-java@v2
        with:
          maven-version: '3.8.1'  # Specify your desired Maven version

      - name: Install Dependencies (Maven)
        run: |
          mvn clean install  # Install dependencies defined in pom.xml

      - name: Run Cucumber Feature
        run: |
          echo "Running feature file: ${{ github.event.inputs.feature }}"
          mvn test -Dcucumber.options="--tags @${{ github.event.inputs.feature }}"