name: Run Selenium BDD Feature Files

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Select a feature file to run'
        required: true
        default: 'RegisterPageTest'  # Default feature file to run
        type: choice  # This creates a dropdown for the user
        options:
          - RegisterPageTest
          - LoginPageTest
          - AnotherFeatureTest
          - all  # Option to run all features

jobs:
  run-feature:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Verify that pom.xml exists (for debugging)
      - name: Verify pom.xml location
        run: |
          echo "Listing directory contents..."
          ls -R  # List all directories and files recursively to find pom.xml

      # Step 3: Set up JDK (Java 21 LTS or Java 17 LTS as fallback)
      - name: Set up JDK (Adoptium Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Java SE 21 (LTS) or change to '17' for Java SE 17 (LTS)
          distribution: 'temurin'  # Use Adoptium Temurin for OpenJDK

      # Step 4: Install Maven separately (fix for 'maven-version' issue)
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven  # Install Maven using apt

      # Step 5: Install project dependencies using Maven
      - name: Install Dependencies (Maven)
        run: |
          mvn clean install  # This installs dependencies from your pom.xml

      # Step 6: Run the selected Cucumber Feature file or all feature files
      - name: Run Cucumber Feature
        run: |
          echo "Running feature files based on input: ${{ github.event.inputs.feature }}"
          
          # Check if the input is 'all' or a specific feature file
          if [ "${{ github.event.inputs.feature }}" == "all" ]; then
            # Run all feature files in the features directory
            mvn test -Dcucumber.options="classpath:features"
          else
            # Run the specific feature file as passed in the input
            mvn test -Dcucumber.options="classpath:features/${{ github.event.inputs.feature }}.feature"
          fi
