- name: Generate Extent Report HTML (Updated Path)
  run: |
    # Generating the report in the updated path: test-output/SparkReport
    mvn clean test -Dcucumber.options="classpath:features" -DextentReports.outputDir=test-output/SparkReport -DextentReports.reportFormat=html

- name: Check report files in the directory
  run: |
    echo "Checking files in the directory where reports are stored"
    ls -l test-output/SparkReport/

- name: Send Test Result Email with Extent Report Attachment
  if: ${{ always() }}  # Ensure it runs even if tests fail
  run: |
    # Define the updated HTML report path with today's date
    TODAY=$(date +'%Y-%m-%d')  # Get today's date in YYYY-MM-DD format
    EXTENT_REPORT_PATH="test-output/SparkReport/spark-report_${TODAY}.html"
    
    # Check if the file exists before proceeding
    if [ ! -f "$EXTENT_REPORT_PATH" ]; then
      echo "Extent report not found! Aborting email sending."
      exit 1
    fi
    
    # Prepare the email body with the report link and personalized signature
    BODY_CONTENT="Hi team. Kindly find the regression report for BrandsHub.<br><br>Thanks and Regards,<br>Gaurav Gupta"
    
    # Send email using SendGrid API with HTML content and the attachment
    curl -X POST "https://api.sendgrid.com/v3/mail/send" \
      -H "Authorization: Bearer $SENDGRID_API_KEY" \
      -H "Content-Type: application/json" \
      -d '{
            "personalizations": [
              {
                "to": [{"email": "'${{ secrets.RECIPIENT_EMAIL }}'"}],
                "subject": "Regression Test Results for BrandsHub"
              }
            ],
            "from": {"email": "'${{ secrets.SENDGRID_SENDER_EMAIL }}'"},
            "content": [
              {
                "type": "text/html",
                "value": "'"${BODY_CONTENT}"'"
              }
            ],
            "attachments": [
              {
                "content": "'$(base64 -w 0 $EXTENT_REPORT_PATH)'",
                "type": "text/html",
                "filename": "Regression-BrandsHub_${TODAY}.html",
                "disposition": "attachment"
              }
            ]
          }'
