name: Run Selenium BDD Feature Files

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Select a feature file to run'
        required: true
        default: 'RegisterPageTest'
        type: choice
        options:
          - RegisterPageTest
          - LoginPageTest
          - all
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  run-feature:
    runs-on: ubuntu-latest

    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
          
          # Step 2: Cache Maven dependencies
          - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Set up JDK (Adoptium Temurin)
      - name: Set up JDK (Adoptium Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 4: Install Maven
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven

      # Step 5: Install project dependencies
      - name: Install Dependencies (Maven)
        run: |
          mvn clean install

      # Step 6: Verify secrets are set (without exposing them)
      - name: Verify secrets are set (without exposing them)
        run: |
          echo "Verifying secrets are available without revealing sensitive data"
          if [ -z "$USER_NAME" ]; then
            echo "USER_NAME is not set"
          fi
          if [ -z "$USER_PASSWORD" ]; then
            echo "USER_PASSWORD is not set"
          fi

      # Step 7: Run the selected Cucumber Feature file or all feature files
      - name: Run Cucumber Feature
        id: run_tests
        run: |
          echo "Running feature files based on input: ${{ github.event.inputs.feature }}"
          if [ "${{ github.event.inputs.feature }}" == "all" ]; then
            mvn test -Dcucumber.options="classpath:features" # Generates a cucumber.json report
          else
            mvn test -Dcucumber.options="classpath:features/${{ github.event.inputs.feature }}.feature"
          fi
          echo "Test execution completed"

      # Step 8: Parse the cucumber.json file to extract scenario counts
      - name: Parse Cucumber Test Results
        id: parse_results
        run: |
          # Install jq to parse JSON
          sudo apt-get install jq

          # Initialize variables for the email body
          EMAIL_BODY="Feature Files Executed:\n\n"
          TOTAL_PASSED=0
          TOTAL_FAILED=0

          # Loop through each feature file and count the passed/failed scenarios
          FEATURE_FILES=$(jq '.elements[].name' target/cucumber.json | sort | uniq)

          for FEATURE in $FEATURE_FILES; do
            FEATURE_NAME=$(echo $FEATURE | sed 's/"//g')
            PASSED=$(jq --arg FEATURE_NAME "$FEATURE_NAME" '.elements[] | select(.name == $FEATURE_NAME) | select(.status == "passed")' target/cucumber.json | wc -l)
            FAILED=$(jq --arg FEATURE_NAME "$FEATURE_NAME" '.elements[] | select(.name == $FEATURE_NAME) | select(.status == "failed")' target/cucumber.json | wc -l)

            # Append the feature file result to the email body
            EMAIL_BODY="$EMAIL_BODY$FEATURE_NAME\nScenarios Passed: $PASSED\nScenarios Failed: $FAILED\n\n"

            # Update total passed and failed counters
            TOTAL_PASSED=$((TOTAL_PASSED + PASSED))
            TOTAL_FAILED=$((TOTAL_FAILED + FAILED))
          done

          # Append the total passed/failed scenarios to the email body
          EMAIL_BODY="$EMAIL_BODY\nTotal Scenarios Passed: $TOTAL_PASSED\nTotal Scenarios Failed: $TOTAL_FAILED"

          # Capture the email body as an environment variable for later use
          echo "EMAIL_BODY=$EMAIL_BODY" >> $GITHUB_ENV

      # Step 9: Send the test result email using Gmail SMTP
      - name: Send Test Result Email
        if: ${{ always() }}  # Ensure it runs even if tests fail
        run: |
          # Send email using Gmail SMTP
          curl --url 'smtp://smtp.gmail.com:587' --ssl-reqd \
            --mail-from "${{ secrets.GMAIL_USERNAME }}" \
            --mail-rcpt "${{ secrets.RECIPIENT_EMAIL }}" \
            --upload-file - \
            --user "${{ secrets.GMAIL_USERNAME }}:${{ secrets.GMAIL_PASSWORD }}" \
            --data-binary "Subject: Test Execution Summary\n\n${{ env.EMAIL_BODY }}"
