name: Run Selenium BDD Feature Files

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger on
  workflow_dispatch:
    inputs:
      feature:
        description: 'Select a feature to run'
        required: true
        type: choice
        options:
          - RegisterPageTest
          - LoginPageTest
          - all
        default: 'all'

permissions:
  contents: read

jobs:
  run-feature:
    runs-on: ubuntu-latest

    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      FEATURE: ${{ github.event.inputs.feature }}  # This will get the feature input from workflow_dispatch or push
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK (Adoptium Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven

      - name: Run Cucumber Feature
        id: run_tests
        run: |
          echo "Running feature files based on input: $FEATURE"
          
          # Ensure FEATURE is not empty
          if [ -z "$FEATURE" ]; then
            echo "FEATURE is empty, defaulting to 'all'"
            FEATURE="all"
          fi
          
          if [ "$FEATURE" == "all" ]; then
            echo "Running all feature files"
            mvn clean test -Dcucumber.options="classpath:features"
          elif [ "$FEATURE" == "RegisterPageTest" ]; then
            echo "Running RegisterPageTest feature"
            mvn clean test -Dcucumber.options="classpath:features/RegisterPageTest.feature"
          elif [ "$FEATURE" == "LoginPageTest" ]; then
            echo "Running LoginPageTest feature"
            mvn clean test -Dcucumber.options="classpath:features/LoginPageTest.feature"
          else
            echo "Invalid feature selected"
            exit 1
          fi

          echo "Test execution completed"

      - name: Generate Test Report
        run: |
          echo "Generating test report..."
          mvn clean verify

      - name: Send Email with Report
        run: |
          EXTENT_REPORT_PATH="target/ExtentReports/extent-report.html"
          curl -X POST "https://api.sendgrid.com/v3/mail/send" \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "personalizations": [
                {
                  "to": [{"email": "'"${{ secrets.RECIPIENT_EMAIL }}"'"}],
                  "subject": "Test Results for Feature: '$FEATURE'"
                }
              ],
              "from": {"email": "'"${{ secrets.SENDGRID_SENDER_EMAIL }}"'"},
              "content": [
                {
                  "type": "text/html",
                  "value": "Hi team. Kindly find the regression report for '$FEATURE'.<br><br>"
                }
              ],
              "attachments": [
                {
                  "content": "'"$(base64 -w 0 $EXTENT_REPORT_PATH)"'",
                  "type": "application/html",
                  "filename": "extent-report.html",
                  "disposition": "attachment"
                }
              ]
            }'
