name: Run Selenium BDD Feature Files

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Select a feature file to run'
        required: true
        default: 'all'
        type: choice
        options:
          - RegisterPageTest
          - LoginPageTest
          - all

permissions:
  contents: read

jobs:
  run-feature:
    runs-on: ubuntu-latest

    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      FEATURE: ${{ github.event.inputs.feature }}  # Correctly pass input as environment variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK (Adoptium Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven

      - name: Install Dependencies (Maven)
        run: |
          mvn clean install

      - name: Run Cucumber Feature
        id: run_tests
        run: |
          echo "Running feature files based on input: $FEATURE"
          if [ "$FEATURE" == "all" ]; then
            mvn clean test -Dcucumber.options="classpath:features"
          elif [ "$FEATURE" == "RegisterPageTest" ]; then
            mvn clean test -Dcucumber.options="classpath:features/RegisterPageTest.feature"
          elif [ "$FEATURE" == "LoginPageTest" ]; then
            mvn clean test -Dcucumber.options="classpath:features/LoginPageTest.feature"
          else
            echo "Invalid feature selected"
            exit 1
          fi
          echo "Test execution completed"
